const TITLES_KEY = "_meta/titles.json";

const escapeHtml = (s) =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

async function loadTitles(env) {
  const obj = await env.BUCKET.get(TITLES_KEY);
  if (!obj) return {};
  try {
    return await obj.json();
  } catch {
    return {};
  }
}

async function saveTitles(env, titles) {
  await env.BUCKET.put(TITLES_KEY, JSON.stringify(titles), {
    httpMetadata: { contentType: "application/json" },
  });
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    const origin = request.headers.get("Origin");
    let allowedOrigin = "https://manager.ahsoorah.fyi";
    if (origin === "http://localhost:5173" || origin === "http://localhost:5174") {
      allowedOrigin = origin;
    }

    const corsHeaders = {
      "Access-Control-Allow-Origin": allowedOrigin,
      "Access-Control-Allow-Methods": "GET, PUT, DELETE, OPTIONS", // PUT added
      "Access-Control-Allow-Headers": "Content-Type, x-api-key",
    };

    if (request.method === "OPTIONS") {
      return new Response(null, { headers: corsHeaders });
    }

    const apiKey = request.headers.get("x-api-key");

    // api routes
    if (url.pathname.startsWith("/api/")) {
      if (apiKey !== env.API_KEY) {
        return new Response("unauthorized", { status: 401, headers: corsHeaders });
      }

      if (url.pathname === "/api/clips" && request.method === "GET") {
        const listed = await env.BUCKET.list({ include: ["customMetadata"] });
        const titles = await loadTitles(env);
        const clips = listed.objects
          .filter((obj) => !obj.key.startsWith("_meta/")) // hide the titles file
          .map((obj) => ({
            name: obj.key,
            size: obj.size,
            uploaded: obj.uploaded,
            customTitle: titles[obj.key] || obj.customMetadata?.title || null,
            url: `https://clips.ahsoorah.fyi/${obj.key}`,
          }));
        return Response.json(clips, { headers: corsHeaders });
      }

      // rename
      if (url.pathname.startsWith("/api/clips/") && request.method === "PUT") {
        const rawFilename = url.pathname.split("/api/clips/")[1];
        if (!rawFilename) return new Response("missing filename", { status: 400, headers: corsHeaders });
        const filename = decodeURIComponent(rawFilename).replace(/[\/\\]/g, "");

        if (!(await env.BUCKET.head(filename))) {
          return new Response("clip not found", { status: 404, headers: corsHeaders });
        }

        let body;
        try {
          body = await request.json();
        } catch {
          return new Response("invalid json", { status: 400, headers: corsHeaders });
        }

        const clean = String(body.customTitle ?? "").trim().slice(0, 200);
        const titles = await loadTitles(env);
        if (clean) titles[filename] = clean;
        else delete titles[filename]; // empty = back to the autogenerated name
        await saveTitles(env, titles);

        return Response.json({ success: true, name: filename, customTitle: clean || null }, { headers: corsHeaders });
      }

      if (url.pathname.startsWith("/api/clips/") && request.method === "DELETE") {
        let rawFilename = url.pathname.split("/api/clips/")[1];
        if (!rawFilename) return new Response("missing filename", { status: 400, headers: corsHeaders });
        const filename = decodeURIComponent(rawFilename).replace(/[\/\\]/g, "");
        await env.BUCKET.delete(filename);

        // clean up its saved title 
        const titles = await loadTitles(env);
        if (titles[filename]) {
          delete titles[filename];
          await saveTitles(env, titles);
        }

        return Response.json({ success: true, deleted: filename }, { headers: corsHeaders });
      }
    }

    // root redirect
    if (request.method === "GET" && url.pathname === "/") {
      return Response.redirect("https://ahsoorah.fyi", 301);
    }

    // discord embed and raw video router
    if (request.method === "GET" && url.pathname !== "/") {
      const path = decodeURIComponent(url.pathname.slice(1));

      if (path.startsWith("_meta/")) return new Response("not found", { status: 404 });

      // if the url has a video extension, serve the raw file from r2
      if (path.match(/\.(mp4|webm|mov|mkv|m4v)$/i)) {
        const object = await env.BUCKET.get(path, { range: request.headers });
        if (!object) return new Response("clip not found", { status: 404 });

        const headers = new Headers();
        object.writeHttpMetadata(headers);
        headers.set("etag", object.httpEtag);
        headers.set("Cache-Control", "public, max-age=31536000");
        headers.set("Accept-Ranges", "bytes");

        // explicitly declare file size and byte range for discord
        if (object.range) {
          headers.set("Content-Range", `bytes ${object.range.offset}-${object.range.offset + object.range.length - 1}/${object.size}`);
        }
        headers.set("Content-Length", object.range ? object.range.length : object.size);

        const status = object.range ? 206 : 200;

        return new Response(object.body, { status, headers });
      }

      // since url is extensionless, search r2 for the real file and its metadata
      const listed = await env.BUCKET.list({ prefix: path, include: ["customMetadata"] });
      const match = listed.objects.find((obj) => {
        const nameWithoutExt = obj.key.substring(0, obj.key.lastIndexOf("."));
        return nameWithoutExt === path;
      });

      if (!match) return new Response("clip not found", { status: 404 });

      // dynamic title generator: saved title -> old metadata title -> name from filename
      const titles = await loadTitles(env);
      let displayTitle = "asura's clip";

      if (titles[match.key]) {
        displayTitle = titles[match.key];
      } else if (match.customMetadata && match.customMetadata.title) {
        displayTitle = match.customMetadata.title;
      } else {
        const lastDashIndex = path.lastIndexOf("-");
        if (lastDashIndex !== -1) {
          let rawName = path.substring(0, lastDashIndex);
          displayTitle = rawName.replace(/[-_]/g, " ");
        }
      }

      const rawVideoUrl = `https://${url.hostname}/${match.key}`;
      const ext = match.key.split(".").pop().toLowerCase();
      const mimeType = ext === "mov" ? "video/quicktime" : ext === "webm" ? "video/webm" : "video/mp4";

      
      const safeTitle = escapeHtml(displayTitle);
      const safeVideoUrl = escapeHtml(rawVideoUrl);

      const html = `
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <title>${safeTitle}</title>
          <meta name="theme-color" content="#8B0000"> 
          
          <meta property="og:site_name" content="asura">
          
          <meta property="og:title" content="${safeTitle}">
          <meta property="og:type" content="video.other">
          <meta property="og:url" content="${escapeHtml(request.url)}">
          
          <meta property="og:video" content="${safeVideoUrl}">
          <meta property="og:video:secure_url" content="${safeVideoUrl}">
          <meta property="og:video:type" content="${mimeType}">
          
          <meta name="twitter:card" content="player">
          <meta name="twitter:player" content="${safeVideoUrl}">
        </head>
        <body style="background: #000; color: #fff; font-family: sans-serif; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0;">
          <p>yo</p>
          <script>
            window.location.replace(${JSON.stringify(rawVideoUrl).replace(/</g, "\\u003c")});
          </script>
        </body>
        </html>
      `;

      return new Response(html, {
        headers: { "Content-Type": "text/html;charset=UTF-8", "Cache-Control": "no-cache" },
      });
    }

    return new Response("not found", { status: 404, headers: corsHeaders });
  },
};
